version: '3.8'

services:
  podtube:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend/instance:/app/instance
      - ./backend/audio_cache:/app/audio_cache
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
